### ISSUE TITLE
请问这个支不支持把打印的Log，写入到本地

### ISSUE THREAD

**Issue by LLQQHH** [getActivity/Logcat#10]
需求场景：
在正式版app，不打印，但是客户端有报错，需要把报错信息写到本地，找个合适的时机上传！有没有LogCat.ToFlie(String erMsg)

**Comment by getActivity** [comment]
小伙子，这个是 Logcat 查看工具，你说的是日志写入，两者是不同的东西，并且框架只在测试环境集成，不建议集成到正式环境。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。
