### ISSUE TITLE
关于日志捕获的范围

### ISSUE THREAD

**Issue by rianlu** [getActivity/Logcat#12]
我发现好像只能获取到java层的日志信息，但是无法获取到 `cpp` 文件里的日志信息

比如我这的情况是：
- `ndk` 中`cpp` 里面的打印信息，打印方式通过引入 `#include <android/log.h>`；
- 本地编译的静态库中的打印信息（也是 `cpp` 文件）

不过我不确定这些信息能不能获取到，android studio控制台是能够获取到的

**Comment by getActivity** [comment]
小伙子，如果你使用原生的 Log 类的 Api 打印不了我可以帮你看看，如果你用其他的方式打印日志，我并不能保证能显示，因为 Logcat 这个库本身用的是命令行来监听，这里面也没有过多的参数可以设置，所以能显示就显示，不能显示我也没有办法。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by rianlu** [comment]
> 小伙子，如果你使用原生的 Log 类的 Api 打印不了我可以帮你看看，如果你用其他的方式打印日志，我并不能保证能显示，因为 Logcat 这个库本身用的是命令行来监听，这里面也没有过多的参数可以设置，所以能显示就显示，不能显示我也没有办法。

是指只能获取通过 `android.util.Log` 类打印的日志对吗😂

**Comment by getActivity** [comment]
是的

**Comment by rianlu** [comment]
> 是的

OK，我明白了，没问题了😄
