### ISSUE TITLE
是否可以增加开关

### ISSUE THREAD

**Issue by dotfeng** [getActivity/Logcat#14]
可以根据需要开启关闭，对离线app的运维很有用

**Comment by getActivity** [comment]
小伙子，我不推荐 Logcat 在线上版本使用，而是在调试模式下使用，关于你这个需求，我表示无法满足，因为一旦涉及到代码动态开关，那么就会存在代码的耦合性，就无法在线上模式环境下完全隔断框架和项目之间的联系，我建议你这边直接 fork 项目代码来自己改。

**Comment by getActivity** [comment]
小伙子，你看看这边还有其他问题不，没有的话我就关闭 issue 了。

**Comment by getActivity** [comment]
超过三天没有响应，关闭此 issue。

**Comment by michaellee123** [comment]
> 小伙子，我不推荐 Logcat 在线上版本使用，而是在调试模式下使用，关于你这个需求，我表示无法满足，因为一旦涉及到代码动态开关，那么就会存在代码的耦合性，就无法在线上模式环境下完全隔断框架和项目之间的联系，我建议你这边直接 fork 项目代码来自己改。

可能不一定是release版本做开关吧，debug版本也有需要开关的情况
