### ISSUE TITLE
大佬，能否动动您的金手指，把日志输出到文件里呀

### ISSUE THREAD

**Issue by DodoSpringLove** [getActivity/Logcat#16]
大佬，能否动动您的金手指，把日志输出到文件里呀

**Comment by DodoSpringLove** [comment]
debug模式下直接看，release模式输出到文件也行，可以通过API自由控制就行

**Comment by getActivity** [comment]
小伙子，目前框架的定位是只针对 debug 模式查看日志，其他情况暂时不考虑，如果你有这个需要，请自行 fork 源码进行修改。
