### ISSUE TITLE
感觉可能是bug，未能显示最近日志，而插入电脑用logcat能看到新的日志

### ISSUE THREAD

**Issue by zhangqi-ulua** [getActivity/Logcat#20]
## 问题描述 

* 框架版本【必填】：最新10.6

* 问题描述【必填】：app中集成后，一开始还挺正常，后面不知道为什么就是不显示最新log（左上角绝对没有点击关闭收集log）

* 复现步骤【必填】：就是很正常操作，只是app静置时间比较长，但打开后，能看到立即打的log，但过一会后就没了（我这里是100%复现，不知道别人那里如何）

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：nexue6P 

* 出现问题的安卓版本【必填】：8.1

## 请回答

* 是部分机型还是所有机型都会出现【必答】：部分

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是（文档中没有提到会遇到此问题）

* issue 是否有人曾提过类似的问题【必答】：否，17个close没有人提过

* 是否可以通过 Demo 来复现该问题【必答】：demo长时间静置会被杀死。我这个是设为忽略电池优化

## 其他

* 提供报错堆栈  无报错，很正常，插入电脑，adb logcat都能显示完整的最新的log

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
@zhangqi-ulua 小伙子，需要你协助确定一下，这个问题是什么机型才会？某个特定的 Android 版本才会？还是某个特定某个品牌才会？还是某个特定的手机型号才会？

**Comment by zhangqi-ulua** [comment]
没有其他手机，帮不了。换其他的框架解决了。关了
