### ISSUE TITLE
log日志长按无法复制内容

### ISSUE THREAD

**Issue by mqj1991076** [getActivity/Logcat#21]
#### 问题描述

* 框架版本：10.6

* 问题描述：log日志长按无法复制内容

* 复现步骤：长按log列表子项，无法复制内容到粘贴板

* 是否必现：是

* 出现问题的手机信息：荣耀V8, 荣耀novia i5pro

* 出现问题的安卓版本：android8.0;  鸿蒙2.0

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：所有

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

**Comment by getActivity** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/28616817/192533846-96533693-4438-4aa1-87e3-a5e2f0fcc0c9.png">


小伙子，明确一下你的问题，你现在的问题是长按后无法弹出这个对话框？还是弹出这个对话框后点击《复制日志》没有办法复制文本？

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。

**Comment by yuntongzhong** [comment]
这个问题我复现了，在小米手机开启传送门（系统功能：长按可以在任意app文字识别）后，log列表页长按松开手指就不会弹出复制日志的弹窗。

**Comment by getActivity** [comment]
@yuntongzhong  小伙子，试试看最新版本会不会？我昨天刚更新了一版，对点击事件和长按事件处理做了优化。
