### ISSUE TITLE
能否效仿chucker库的集成方式,放开日志入口

### ISSUE THREAD

**Issue by ljwx** [getActivity/Logcat#23]
#### 建议收集

* issue 是否有人曾提过类似的问题？【必答】（一旦出现重复提问我将不会再次解答）
否

* 框架文档是否有提及到此问题？【必答】：是/否（请先看完框架的文档后再来提建议）
否

* 你觉得框架有什么不足之处？【必答】（你可以描述框架有什么令你不满意的地方）
虽然代码侵入性为0, 但首页的悬浮图标,或者通知栏常驻, 这两种入口方式依然让人觉得侵入性很强. 
因为以我的经验(虽然不丰富),日常开发中,我在AS调试日志更为常见,手机端筛选日志频率不会太高. 
如果因为一个不太高频率的操作而一直常驻首页或通知栏,真的会影响我考虑是否使用该库. 

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）
作者能效仿 https://github.com/ChuckerTeam/chucker 这个库的集成方式吗.
让开发者自已定义日志查看入口,但只在debug模式下响应,release模式不响应.
如果作者还是无法接受,希望还是0代码入侵,是否可以提供两种集成方式呢.
一种0入侵,一种自由定义,但多一步操作.
虽然自己fork一份修改也能满足需求,但不管是希望作者的库更优秀,还是怕麻烦,我都希望作者能响应😂
衷心感谢!

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
