### ISSUE TITLE
按home键app进入后台，再点击通知栏进入日志调试界面后，app会销毁重建

### ISSUE THREAD

**Issue by imkkdev** [getActivity/Logcat#24]
#### 问题描述

* 框架版本【必填】：11.2

* 问题描述【必填】：按home键app进入后台，再点击通知栏进入日志调试界面后，app会销毁重建

* 复现步骤【必填】：打开app，按home键app进入后台，再点击通知栏进入日志调试界面后，按日志页面右上角回退（或者home键），会直接返回桌面，再按app图标，app会被新建，之前app会销毁。

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：红米 K30s

* 出现问题的安卓版本【必填】：ANDROID 12

* 问题信息的来源渠道【必填】：自己操作，github demo 可直接复现。

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：未知

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】： 否

* 是否可以通过 Demo 来复现该问题【必答】：是

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by imkkdev** [comment]
> 小伙子，我这边根据你提供的复现步骤，在小米 12 Android 13 的手机上面确实可以复现到该问题，使用 Android 11 官方模拟器也有这个问题，但是 Android 10 模拟器就没有这个问题，这个问题大概率可能是系统的 Bug，我自己的话尝试了几种办法进行修复，仍然没有效果，就当我去 debug 代码的时候，发现无法通过堆栈追踪到具体的代码。
> 
> <img alt="image" width="1680" src="https://user-images.githubusercontent.com/28616817/230104568-54edca47-a1a2-4c78-a132-2650d039cc55.png">
> 
> 我对这个问题暂时没有什么好的解决方案，建议你换成悬浮窗的方式来实现，当然你要是有解决方案也可以分享给我。

去掉 logcat activity的 singleInstance launchMode 就没这个问题了，不知是否可行

**Comment by getActivity** [comment]
不可行，这个办法我也有试过，但是 LogcatActivity 每次进来都会被销毁重建

**Comment by getActivity** [comment]
超过一个星期没有响应，自动关闭此 issue。
