### ISSUE TITLE
过滤标签的内容能否适配大小写

### ISSUE THREAD

**Issue by fuchengxin** [getActivity/Logcat#25]
#### 建议收集

* issue 是否有人曾提过类似的问题？否

* 框架文档是否有提及到此问题？否

* 你觉得框架有什么不足之处？过滤器的字母希望能忽略大小写，目前大小写不同是搜不到相关日志的

* 你觉得该怎么去完善会比较好？【非必答】（你可以提供一下自己的想法或者做法供作者参考）

**Comment by getActivity** [comment]
收到，多谢小伙子的建议，这个功能会在下个版本进行优化。

**Comment by fuchengxin** [comment]
11.3新版本，过滤器的字母全部都忽略成小写了，即便是指定的tag 如“Raw”,必须输入"raw"才能搜索，大写搜索不出来了

**Comment by getActivity** [comment]
@fuchengxin 小伙子，经过测试，确实存在这个问题，目前已经在 [11.5](https://github.com/getActivity/Logcat/releases/tag/11.5) 版本上面修复了，可以更新版本再试试看。

**Comment by fuchengxin** [comment]
能否将打印的横向滑动的text改为点击展开那种，一个请求返回值的打印有点长，横向滑动体验不太好

**Comment by getActivity** [comment]
小伙子，一行显示不是会更直观一点？虽然说那种超长一行的文本也有，但是出现情况比较少，我认为还是可以接受的。

**Comment by fuchengxin** [comment]
就我目前碰到的接口请求都是超长的，因为后台返的最基础的数据都是{"code" : 0, "data": {} , "message" : "string" , "success" : true }，这个长度已经快超过屏幕了，如果data里面稍微包几个对象  那就特别长了，我们的接口数据经常要滑半天，或者复制出去看数据

**Comment by getActivity** [comment]
小伙子，这个问题我已经处理了，你升级到框架最新版本再试试看。

**Comment by fuchengxin** [comment]
感谢轮子哥，已经可以了
