### ISSUE TITLE
日志过多会卡死页面

### ISSUE THREAD

**Issue by fuchengxin** [getActivity/Logcat#26]
#### 问题描述

* 框架版本【必填】：11.2

* 问题描述【必填】：如果日志过多，打开记录日志的页面就会被卡死

* 复现步骤【必填】：XXX

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：荣耀X40 GT

* 出现问题的安卓版本【必填】：12

* 问题信息的来源渠道【必填】：自己遇到的

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：是

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by getActivity** [comment]
小伙子，你说的卡死是指 ANR？

**Comment by fuchengxin** [comment]
是的，我们项目日志比较多，一段时间之后进入日志页面，就会anr卡死

**Comment by fuchengxin** [comment]
[anr.zip](https://github.com/getActivity/Logcat/files/12101918/anr.zip)
这是ANR日志文件

> @fuchengxin 小伙子，麻烦导出 ANR 的日志给到我。

**Comment by getActivity** [comment]
小伙子，问题已经修复了，你可以升级到 11.3 版本再看一下。

**Comment by getActivity** [comment]
超过三个星期没有响应，自动关闭此 issue。
