### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by jiangyongandy** [getActivity/Logcat#27]
#### 问题描述

* 框架版本【必填】：11.2

* 问题描述【必填】：依赖找不到

* 复现步骤【必填】：gradle7.4 rebuild

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：请填写出现问题的品牌和机型

* 出现问题的安卓版本【必填】：请填写出现问题的 Android 版本

* 问题信息的来源渠道【必填】：请填写问题的来源（例如：自己遇到的/Bugly 看到的/用户反馈等等）

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：部分/全部（例如：某为，某 Android 版本会出现）

* 框架最新的版本是否存在这个问题【必答】：是/否（如果用的是旧版本的话，建议升级看问题是否还存在）

* 是否已经查阅框架文档还未能解决的【必答】：是/否（文档会提供最常见的问题解答，可以看看是否有自己想要的）

* issue 是否有人曾提过类似的问题【必答】：是/否（看看曾经有人提过类似的问题，先参考一下别人是怎么解决的）

* 是否可以通过 Demo 来复现该问题【必答】：是/否（排查一下是不是自己的项目代码写得有问题导致的）

#### 其他

* 提供报错堆栈  Could not find com.github.getActivity:XToast:8.9.
     Searched in the following locations:
       - https://repo1.maven.org/maven2/com/github/getActivity/XToast/8.9/XToast-8.9.pom
       - https://maven.aliyun.com/repository/public/com/github/getActivity/XToast/8.9/XToast-8.9.pom
       - https://maven.aliyun.com/repository/google/com/github/getActivity/XToast/8.9/XToast-8.9.pom
       - https://repo.huaweicloud.com/repository/maven/com/github/getActivity/XToast/8.9/XToast-8.9.pom
       - https://jitpack.io/com/github/getActivity/XToast/8.9/XToast-8.9.pom
       - https://repo.maven.apache.org/maven2/com/github/getActivity/XToast/8.9/XToast-8.9.pom
       - https://dl.google.com/dl/android/maven2/com/github/getActivity/XToast/8.9/XToast-8.9.pom
       - https://jcenter.bintray.com/com/github/getActivity/XToast/8.9/XToast-8.9.pom

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）com.github.getActivity:XToast:8.9. 作者的这个库不在仓库了吗，还是换名了

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
