### ISSUE TITLE
[Bug]：三星手机通知栏不显示问题

### ISSUE THREAD

**Issue by fuchengxin** [getActivity/Logcat#29]
### 框架版本【必填】

11.3

### 问题描述【必填】

三星手机在安卓12以上通知栏不能正常显示

### 复现步骤【必填】

打开即可复现

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

31

### 出现问题的手机信息【必填】

三星A54

### 出现问题的安卓版本【必填】

13

### 是部分机型还是所有机型都会出现【必答】

部分

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供解决方案

此问题是在LogcatService使用pendingIntentFlag版本判断问题，将安卓12以上的pendingIntentFlag = PendingIntent.FLAG_MUTABLE; 改为pendingIntentFlag = PendingIntent.FLAG_IMMUTABLE;  就能正常显示通知栏了

**Comment by getActivity** [comment]
小伙子，问题修复了，更新到 [11.5](https://github.com/getActivity/Logcat/releases/tag/11.5) 版本再试试看。

**Comment by fuchengxin** [comment]
java.lang.RuntimeException: Unable to start service com.hjq.logcat.LogcatService@670729d with Intent { cmp=com.jingmai.video.live/com.hjq.logcat.LogcatService }: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{1054dd5 8060:com.jingmai.video.live/u0a183} targetSDK=34
大佬，这里没有适配安卓14

**Comment by getActivity** [comment]
小伙子，问题修复了，你用上面的包再试试看。
