### ISSUE TITLE
适配有问题

### ISSUE THREAD

**Issue by RuralDeer** [getActivity/Logcat#3]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/12441381/100591189-5f955100-3330-11eb-83da-9b2f8dd4903c.png">
集成后变得好大

**Comment by getActivity** [comment]
你的项目有用 AutoSize ？

**Comment by RuralDeer** [comment]
轮子哥牛人，刚想到项目中用了AutoSize

**Comment by getActivity** [comment]
你在 AutoSize 设置不去适配 LogcatActivity 即可
