### ISSUE TITLE
[疑惑]：使用线上版打包出错

### ISSUE THREAD

**Issue by SmallRedSister** [getActivity/Logcat#30]
### 问题描述【必填】

使用线上版打包出错，依赖添加的是implementation 'com.github.getActivity:Logcat:11.5' //线上测试版
具体错误如下：
 error: failed linking references.

AS环境：
minSdk 21
targetSdk 33
version '8.0.2'
gradle-8.0

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by SmallRedSister** [comment]
kotlinOptions {
        jvmTarget = '11'
    }

**Comment by getActivity** [comment]
小伙子，编译出错这种只能你自己看了，我又没有你的源码，加上我自己本地跑又是正常，除非你自己排查到问题，并且确定是框架的问题，再反馈给我处理。

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
