### ISSUE TITLE
页面显示多个入口

### ISSUE THREAD

**Issue by songshuilin** [getActivity/Logcat#31]
### 框架版本【必填】

11.8

### 问题描述【必填】

页面显示多个入口

### 复现步骤【必填】

正常集成这个框架，然后运行打开一个activity就显示一个入口，这个activity是透明的。

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

32

### 出现问题的手机信息【必填】

mumu模拟器

### 出现问题的安卓版本【必填】

9

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

是所有机型

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

![1695109795577](https://github.com/getActivity/Logcat/assets/18466715/bdd1b66d-6014-41c1-b1f8-59d5348009e1)

**Comment by getActivity** [comment]
[Logcat-11.9.aar.zip](https://github.com/getActivity/Logcat/files/12669533/Logcat-11.9.aar.zip)

**Comment by getActivity** [comment]
小伙子，问题处理了，你下载上面的包试试看

**Comment by getActivity** [comment]
另外如果有出现类报找不到的情况，则需要添加 [EasyWindow](https://github.com/getActivity/EasyWindow)  依赖

dependencies {
    // 悬浮窗框架：https://github.com/getActivity/EasyWindow
    implementation 'com.github.getActivity:EasyWindow:10.3'
}

**Comment by getActivity** [comment]
超过两个星期没有响应，自动关闭此 issue。
