### ISSUE TITLE
[Bug]：同一个tag类型的多条日志不会显示到面板上面

### ISSUE THREAD

**Issue by df13954** [getActivity/Logcat#32]
### 框架版本【必填】

11.8

### 问题描述【必填】

在Main中增加一个线程，不断打印日志，进入log面板查看日志输出情况，发现只会输出部分，不会持续输出。
![screen_cap_20231122_100729](https://github.com/getActivity/Logcat/assets/18607031/6783d295-c8e0-4330-958a-09919b6c93ed)
![screen_cap_20231122_100741](https://github.com/getActivity/Logcat/assets/18607031/13aab82d-ab5c-4c0d-8189-f43a17e4e10f)

### 复现步骤【必填】

Main中onCreate调用打印日志printLog()
这里是打印日志的代码。
```
    private static final String TAG = "MainActivity";
    int i = 0;
    boolean run = true;
    private void printLog() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                // 持续打日志,看看内存变化
                try {
                    while (run) {
                        Thread.sleep(150);
                        i++;
                        Log.i(TAG, "run: " + i);
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }
```

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

pixel3

### 出现问题的安卓版本【必填】

12

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

pixel3，6,Android12和13

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
拉取项目main最新代码，增加上面的测试打印log代码，进入log面板查看日志可复现。
```

### 提供解决方案

```
com.hjq.logcat.LogcatAdapter#addItem
# 这段代码判断出bug

        if (!mShowData.isEmpty()) {
            LogcatInfo lastInfo = getItem(mShowData.size() - 1);
            if (info.getLevel().equals(lastInfo.getLevel()) &&
                    info.getTag().equals(lastInfo.getTag())) {
                // 追加日志
                lastInfo.addLogContent(info.getContent());
                if (Looper.myLooper() == Looper.getMainLooper()) {
                    notifyItemChanged(mShowData.size() - 1);
                }
                return;
            }
        }

```

**Comment by getActivity** [comment]
小伙子，我理解你说的问题，应该是日志行数太多了，被收缩了吧，你点右边的 `V` 按钮，就能完全展示了

<img width="802" alt="image" src="https://github.com/getActivity/Logcat/assets/28616817/046853f7-9120-49c7-9bbd-2b28d0b8f50b">

**Comment by df13954** [comment]
明白了，点右边icon可以展开看到日志了，感谢。
