### ISSUE TITLE
[Bug]：集成以后gradle编译报错，EasyWindow:10.3依赖下载不到

### ISSUE THREAD

**Issue by ladmini** [getActivity/Logcat#33]
### 框架版本【必填】

11.8

### 问题描述【必填】

Gradle集成11.8，编译的时候报错，一直提示下面的错误
```java
Failed to resolve: com.github.getActivity:EasyWindow:10.3
```

Demo编译的时候也有这个问题，但是如果我把Demo中Library引用的EasyWindow:10.3换成EasyWindow:10.5就可以编译通过了，只不过可能在10.5以后有一些API发生变化，需要注释下面2行Demo才可以跑起来。
```java
//import com.hjq.window.draggable.SpringDraggable;
//setDraggable(new SpringDraggable());
```

Issue里面有2类似的问题 #27 和 #28 但是不是关于EasyWindow的。

### 复现步骤【必填】

新建项目，在dependencies加入下面这行代码，点击**Sync Now**，一会以后build就出错了
```java
debugImplementation 'com.github.getActivity:Logcat:11.8'
```

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

33

### 出现问题的手机信息【必填】

OPPO

### 出现问题的安卓版本【必填】

Android 10.0

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

全部

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供截图或视频

<img width="1391" alt="截屏2023-11-23 09 22 18" src="https://github.com/getActivity/Logcat/assets/5718706/dc053912-6973-4aca-a82a-467dbdd0bd3e">

**Comment by getActivity** [comment]
小伙子，这个问题修复了，升级 [11.82](https://github.com/getActivity/Logcat/releases/tag/11.82) 再试一下。

**Comment by ladmini** [comment]
大佬，除了说一句粗俗的🐮🍺，我找不出更华丽的语言来表达我此刻对你的敬佩！确认已经解决了，看了一下你的很多其它框架，我决定都换成你的，比如[AndroidProject-Kotlin](https://github.com/getActivity/AndroidProject-Kotlin)，也决定学习一下你的[AndroidProject-Kotlin](https://github.com/getActivity/AndroidProject-Kotlin)感谢🙏
