### ISSUE TITLE
有没有接入可以将日志推送到后台[疑惑]：

### ISSUE THREAD

**Issue by actJacky** [getActivity/Logcat#34]
### 问题描述【必填】

有没有接入可以将日志推送到后台：
1、日常的打印日志？
2、异常的错误Exception传入后台方便查看？

### 框架文档是否提及了该问题【必答】

未选择

### 是否已经查阅框架文档但还未能解决的【必答】

未选择

### issue 列表中是否有人曾提过类似的问题【必答】

未选择

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

未选择

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

请重新提一个 issue 并纠正以上问题
