### ISSUE TITLE
[疑惑]：不知道是不是compileSdkVersion31的问题，编译报错

### ISSUE THREAD

**Issue by JohnWayneHong** [getActivity/Logcat#39]
### 问题描述【必填】

![微信截图_20240828110502](https://github.com/user-attachments/assets/b95cd2ac-24b2-48cf-9609-c8acb29eb8ce)

具体报错内容为
AAPT: error: 'specialUse' is incompatible with attribute foregroundServiceType (attr) flags [camera=64, connectedDevice=16, dataSync=1, location=8, mediaPlayback=2, mediaProjection=32, microphone=128, phoneCall=4].\n    ","tool":"AAPT"}

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

**Comment by getActivity** [comment]
你把 compileSdkVersion 改成 34 再试一下

**Comment by JohnWayneHong** [comment]
> 你把 compileSdkVersion 改成 34 再试一下

可以了，换成34不报错了
