### ISSUE TITLE
[Bug]：11.86   ide右侧Gradle执行assembleProfile 编译不通过   

### ISSUE THREAD

**Issue by w296365959** [getActivity/Logcat#40]
### 框架版本【必填】

11.85没问题，升级到11.86报错

### 问题描述【必填】

编辑不通过

### 复现步骤【必填】

依赖方式 自定义了 buildTypes profile 类型
然后使用profileImplementation  依赖报上述错误

### 是否必现【必填】

未选择

### 项目 targetSdkVersion【必填】

30

### 出现问题的手机信息【必填】

编辑不通过

### 出现问题的安卓版本【必填】

编辑不通过

### 是部分机型还是所有机型都会出现【必答】

必现

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

是

### issue 列表中是否有人曾提过类似的问题【必答】

否

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

是

### 提供报错堆栈

```text
app\build\intermediates\packaged_manifests\devProfile\universal\AndroidManifest.xml:4440: error: 'specialUse' is incompatible with attribute foregroundServiceType (attr) flags [camera=64, connectedDevice=16, dataSync=1, location=8, mediaPlayback=2, mediaProjection=32, microphone=128, phoneCall=4].
     error: failed processing manifest.
```

### 提供解决方案

回退到11.85正常

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 没有严格按照 issue 模板填写问题

* 看似回答了问题，但是实际是乱回答，没有认真去核实问题就乱回答

请重新提一个 issue 并纠正以上问题
