### ISSUE TITLE
打开logcat会将MainActivity给pause住的问题

### ISSUE THREAD

**Issue by sdfwds4** [getActivity/Logcat#5]
比较找到的好几个logcat库，最后发现是这个库最好，集成简单，界面好看，而且有人维护。

有一个问题：我是想集成该库到游戏里，游戏里用MainActivity，当点开logcat的时候出现了新的Activity会将游戏给pause住，能不能不创建新的Activity，不把游戏给pause住？

像这个库一样：
https://github.com/fatangare/LogcatViewer

**Comment by getActivity** [comment]
不能，因为你说的这个库是用 Dialog 实现的，所以没有这种情况出现，而框架采用的是单独的 Activity，所以没办法做到。而换成 Dialog 需要考虑获取权限请求回调的问题，修改成本比较高，经过认真斟酌，暂不考虑替换。

**Comment by getActivity** [comment]
当然你也可以通过 fork 本仓库来修改

**Comment by sdfwds4** [comment]
我对Android开发不太熟悉，你说的那样改我不会改ToT。只能参考你这个库来改https://github.com/fatangare/LogcatViewer了，用了你的xtoast，好用的很！

谢谢！！！！！
