### ISSUE TITLE
游戏打印的log无法捕获

### ISSUE THREAD

**Issue by sdfwds4** [getActivity/Logcat#6]
使用游戏引擎打印的log无法捕获。

见demo，注意右边绿色机器人按钮下面的黑色按钮，双击打开。
[egret-demo_android.zip](https://github.com/getActivity/Logcat/files/5756668/egret-demo_android.zip)

**Comment by getActivity** [comment]
游戏引擎最终调用的是原生的日志打印？

**Comment by sdfwds4** [comment]
不清楚，AS调试是有日志打印，另一个黑色按钮打开的logcatviewer也是可以捕获得到的

**Comment by getActivity** [comment]
如果不确定的话，我就关闭 issue 了，如果原生 Log 无法打印的问题随时欢迎你来找我，但是游戏打印 Log 这种我无法给你保证是否能打印出来。
