### ISSUE TITLE
非常想知道你是如何做到不需要初始化的

### ISSUE THREAD

**Issue by ytxyyt** [getActivity/Logcat#8]
不用调用是如何启动的呢？

**Comment by getActivity** [comment]
利用 ContentProvider 去做的，具体实现你可以看一下这个类 [InitProvider.java](https://github.com/getActivity/Logcat/blob/master/library/src/main/java/com/hjq/logcat/InitProvider.java)

**Comment by getActivity** [comment]
小伙子，你这边还有其他问题不，没有的话我就关闭 issue 了。
