### ISSUE TITLE
规范

### ISSUE THREAD

**Issue by jupengfei-github** [getActivity/Logcat#9]
您好，我也是Android开发的从业者，想咨询下您，在日志打印这块，有没有完整的行业规范可以参考的，感觉这块没有规范的话，很容易就出现莫名其妙的问题

**Comment by getActivity** [comment]
小伙子，我不清楚你说的莫名其妙的问题是指什么？

**Comment by getActivity** [comment]
长时间没有响应，关闭此 issue。
